version: "3.3"

services:
  moodleapp:
    build:
      context: .
    image: moodleapp:1.0
    ports:
      - "8080:80"                # use 8080 on host to avoid conflicts
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - moodledb
    restart: unless-stopped
    networks:
      - moodlenet

  moodledb:
    image: mysql:8.0.36         # official MySQL 8.0.x; 8.4 not available
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - clouddbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - moodlenet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: moodledb           # use service name, not container_name
      PMA_PORT: "3306"
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - moodledb
    networks:
      - moodlenet

volumes:
  clouddbdata:
  moodledata:

networks:
  moodlenet:
    driver: bridge